export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EXTRA = "LOGIN_EXTRA";

export const FETCH_START = "FETCH_START";
export const FETCH_FAIL = "FETCH_FAIL";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const ERROR = "ERROR";
export const ERROR_CLEAR = "ERROR_CLEAR";

export const CREATE_REVIEW_START = "CREATE_REVIEW_START";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";

export const NEW_REVIEW = "NEW_REVIEW";
export const NEW_REVIEW_DONE = "NEW_REVIEW_DONE";

export const CREATE_ADMIN_START = "CREATE_ADMIN_START";
export const CREATE_ADMIN_FAIL = "CREATE_ADMIN_FAIL";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";

export const IS_ADMIN = "IS_ADMIN";
