export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
